// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueueSystem.Api.Data;

#nullable disable

namespace QueueSystem.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430135755_AddSimulationRunScenario")]
    partial class AddSimulationRunScenario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("QueueSystem.Api.Models.BankService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvgServiceTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrowdHighStartsAtPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CrowdMediumStartsAtPercent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("OvercrowdStartsAtPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("branch", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StaffAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StaffId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("counter", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.CrowdLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrowdLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCustomers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("crowd_log", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ArrivalUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSimulated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueTicketId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QueueTicketId")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.DailyReportAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgWaitMinutes")
                        .HasColumnType("REAL");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BusiestServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PeakHour")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCustomersServed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusiestServiceId");

                    b.HasIndex("BranchId", "ReportDate")
                        .IsUnique();

                    b.ToTable("report", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.PredictionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveCounters")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgServiceMinutesInput")
                        .HasColumnType("REAL");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("EstimatedAvgWaitMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimatedClearingMinutes")
                        .HasColumnType("REAL");

                    b.Property<int>("QueueLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceId");

                    b.ToTable("prediction_log", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.QueueAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CounterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueueTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleasedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.HasIndex("QueueTicketId", "ReleasedUtc");

                    b.ToTable("queue_assignment", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.QueueDaySequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BranchId", "ServiceId", "DateUtc")
                        .IsUnique();

                    b.ToTable("queue_day_sequence", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.QueueTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CalledUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CounterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecalledUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BranchId", "Status", "ServiceId");

                    b.ToTable("queue", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.SimulationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FixedServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneratedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Scenario")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartedByStaffId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("FixedServiceId");

                    b.HasIndex("StartedByStaffId");

                    b.ToTable("simulation_run", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("LoginEmail")
                        .IsUnique();

                    b.ToTable("staff", (string)null);
                });

            modelBuilder.Entity("QueueSystem.Api.Models.Counter", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.BankService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("Service");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.CrowdLog", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.Customer", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.QueueTicket", "QueueTicket")
                        .WithMany()
                        .HasForeignKey("QueueTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueTicket");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.DailyReportAggregate", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.BankService", "BusiestService")
                        .WithMany()
                        .HasForeignKey("BusiestServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("BusiestService");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.PredictionLog", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.BankService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.QueueAssignment", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Counter", "Counter")
                        .WithMany()
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.QueueTicket", "QueueTicket")
                        .WithMany()
                        .HasForeignKey("QueueTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("QueueTicket");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.QueueDaySequence", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.BankService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.QueueTicket", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.Counter", "Counter")
                        .WithMany()
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QueueSystem.Api.Models.BankService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Counter");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.SimulationRun", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QueueSystem.Api.Models.BankService", "FixedService")
                        .WithMany()
                        .HasForeignKey("FixedServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QueueSystem.Api.Models.Staff", "StartedByStaff")
                        .WithMany()
                        .HasForeignKey("StartedByStaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("FixedService");

                    b.Navigation("StartedByStaff");
                });

            modelBuilder.Entity("QueueSystem.Api.Models.Staff", b =>
                {
                    b.HasOne("QueueSystem.Api.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });
#pragma warning restore 612, 618
        }
    }
}
